version: '3'
services:
  redmine:
    image: redmine-dev
    build:
      context: .
      target: base
    environment:
      - RAILS_ENV=development
      - REDMINE_PLUGINS_MIGRATE=1
      - REDMINE_DB_MYSQL=mariadb
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_DATABASE=bitnami_redmine_development
      - REDMINE_SECRET_KEY_BASE=supersecretkey
      - REDMINE_LANG=es
    volumes:
      - './always_restart.txt:/usr/src/redmine/plugins/tmp/always_restart.txt'
      - './:/usr/src/redmine/plugins/dss_pnrp'
      - 'redmine_data:/usr/src/redmine/files'
  mariadb:
    volumes:
      - 'mariadb_data:/bitnami/mariadb/'
      - './init-develop-database.sql:/docker-entrypoint-initdb.d/init-develop-database.sql'
