version: '3'
services:
  mariadb:
    restart: always
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    volumes:
      - 'mariadb_data:/bitnami'
  redmine:
    image: 'bitnami/redmine:4.2.0'
    environment:
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
    ports:
      - '8080:3000'
    volumes:
      - 'redmine_data:/bitnami'
      - '../:/bitnami/redmine/plugins/dss_pnrp'
    depends_on:
      - mariadb

volumes:
  redmine_data:
    driver: local
  mariadb_data:
    driver: local
